# Generated by Django 4.2.4 on 2023-08-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(max_length=100, null=True, verbose_name='сделано в'),
        ),
    ]
